#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xd358;
constexpr uint24_t FX_DATA_BYTES = 2922350;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t abutton = 0x000000;
constexpr uint24_t dpad = 0x000062;
constexpr uint24_t monsters = 0x0001E4;
constexpr uint24_t namesgray = 0x0956A6;
constexpr uint24_t nameswhite = 0x0C0128;
constexpr uint24_t shinymonsters = 0x0EABAA;
constexpr uint24_t textentries = 0x18006C;
